// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function boundGaussian() {
  while(true) {
    var u = 1 - Math.random();
    var v = Math.random();
    var z = Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * 3.14159265 * v);
    var scaled = z / 10.0 + 0.5;
    if (!(scaled < 0 || scaled > 1)) {
      return scaled;
    }
    _param = undefined;
    continue ;
  };
}

function tournamentConstruction(d) {
  var _t = [0];
  var _depth = d - 1 | 0;
  while(true) {
    var depth = _depth;
    var t = _t;
    var level = t.length;
    var rank = Belt_Array.concatMany(t.map((function(level){
            return function (v) {
              return [
                      v,
                      ((level << 1) - v | 0) - 1 | 0
                    ];
            }
            }(level))));
    if (depth <= 0) {
      return rank;
    }
    _depth = depth - 1 | 0;
    _t = rank;
    continue ;
  };
}

function genPlayers() {
  var players = Core__Array.make(64, 0).map(function (param) {
        return boundGaussian();
      });
  console.log(players);
}

genPlayers();

console.log(tournamentConstruction(2));

function App(props) {
  return JsxRuntime.jsx("div", {
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
